# ----------------------- #
#      Main Configs       #
# ----------------------- #
name:           Grand Tour Project
description:    "The Galileo Correspondence Project is a collaborative digital humanities research initiative to create a rich database from the work of a team of graduate student researchers, directed by Paula Findlen and Hannah Marcus, and ultimately a monograph about both the metadata and content of the letters of Galileo Galilei."
baseurl:

# Options
root:           /
destination:    ./_site
highlighter:    pygments

permalink:      /blog/:title/
markdown:       redcarpet
markdown_ext:   md