# ----------------------- #
#      Main Configs       #
# ----------------------- #

name:           The Grand Tour Project

name:           "The Grand Tour Project"

description:    "A digital study of the journeys and lives of eighteenth-century travelers to Italy directed by Giovanna Ceserani"
baseurl:

# Options
root:           /
destination:    ./_site
highlighter:    pygments

permalink:      /blog/:title/
markdown:       redcarpet
markdown_ext:   md
