# ----------------------- #
#      Main Configs       #
# ----------------------- #

name:           The Grand Tour Project

name:           "Grand Tour Project"

description:    "The Grand Tour Project is a collaborative digital humanities project dedicated to creating a searchable database based on John Ingamell's Dictionary of British and Irish Travelers to Italy"
baseurl:

# Options
root:           /
destination:    ./_site
highlighter:    pygments

permalink:      /blog/:title/
markdown:       redcarpet
markdown_ext:   md
